defaults: &defaults
  adapter: mysql2
  host: localhost
  username: root
  password: root

development:
  <<: *defaults
  database: shop2t_development

test: &test
  <<: *defaults
  database: shop2t_test

production:
  <<: *defaults
  database: shop2t_development

cucumber:
  <<: *test