website:
  name: 2threads Finds
collection:
  per_page: 20
product:
  image:
    width: 620
    height: 240
    thumbnail:
      width: 78
      height: 30
retailer:
  logo:
    width: 200
    height: 80
invite:
  credit: 10